"""
services/pdf_service.py
=======================
PDF Generation using WeasyPrint.
"""

import os
from pathlib import Path
from datetime import datetime

# Attempt to import weasyprint. If not installed, mock it.
try:
    from weasyprint import HTML
except ImportError:
    HTML = None

MEDIA_DIR = Path("/app/media/pdfs")
MEDIA_DIR.mkdir(parents=True, exist_ok=True)

def _generate_pdf(html_content: str, filename: str) -> str:
    filepath = MEDIA_DIR / filename
    if HTML:
        HTML(string=html_content).write_pdf(target=str(filepath))
    else:
        # Fallback for systems without WeasyPrint/Pango installed
        with open(filepath, "w") as f:
            f.write("PDF Generation requires WeasyPrint.\nHTML Content:\n" + html_content)
    return f"media/pdfs/{filename}"

def _build_html(title: str, doc_number: str, doc_date: str, vendor, line_items, doc_obj, po_ref="") -> str:
    # Common HTML template for PO and Invoice
    items_html = ""
    for item in line_items:
        # handle difference between PO line item and Invoice line item
        desc = getattr(item, "product_name", getattr(item, "description", ""))
        items_html += f"""
        <tr>
            <td>{desc}</td>
            <td>{item.quantity}</td>
            <td>${item.unit_price}</td>
            <td>${item.total_price}</td>
        </tr>
        """
        
    tax_html = ""
    if getattr(doc_obj, "igst", 0) > 0:
        tax_html = f"<tr><td colspan='3'>IGST:</td><td>${doc_obj.igst}</td></tr>"
    else:
        cgst = getattr(doc_obj, "cgst", getattr(doc_obj, "tax_amount", 0) / 2)
        sgst = getattr(doc_obj, "sgst", getattr(doc_obj, "tax_amount", 0) / 2)
        tax_html = f"""
        <tr><td colspan='3'>CGST:</td><td>${cgst}</td></tr>
        <tr><td colspan='3'>SGST:</td><td>${sgst}</td></tr>
        """

    po_ref_html = f"<p><strong>PO Reference:</strong> {po_ref}</p>" if po_ref else ""

    return f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; padding: 40px; color: #333; }}
            .header {{ border-bottom: 2px solid #0056b3; padding-bottom: 20px; margin-bottom: 30px; }}
            .header h1 {{ margin: 0; color: #0056b3; }}
            .details {{ margin-bottom: 30px; }}
            .details p {{ margin: 5px 0; }}
            table {{ width: 100%; border-collapse: collapse; margin-bottom: 30px; }}
            th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
            th {{ background-color: #f8f9fa; }}
            .totals {{ text-align: right; font-weight: bold; }}
            .totals td {{ border: none; }}
            .footer {{ margin-top: 50px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>VendorBridge ERP</h1>
            <h2>{title}</h2>
        </div>
        
        <div class="details">
            <p><strong>Document Number:</strong> {doc_number}</p>
            <p><strong>Date:</strong> {doc_date}</p>
            {po_ref_html}
            <br>
            <p><strong>Vendor:</strong> {vendor.company_name}</p>
            <p><strong>Email:</strong> {vendor.email}</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {items_html}
            </tbody>
            <tfoot class="totals">
                <tr>
                    <td colspan="3">Subtotal:</td>
                    <td>${doc_obj.subtotal}</td>
                </tr>
                {tax_html}
                <tr>
                    <td colspan="3">Grand Total:</td>
                    <td>${doc_obj.grand_total}</td>
                </tr>
            </tfoot>
        </table>

        <div class="footer">
            Generated by VendorBridge ERP
        </div>
    </body>
    </html>
    """

def generate_po_pdf(purchase_order, line_items, vendor) -> str:
    html = _build_html(
        title="Purchase Order",
        doc_number=purchase_order.po_number,
        doc_date=purchase_order.created_at.strftime("%Y-%m-%d"),
        vendor=vendor,
        line_items=line_items,
        doc_obj=purchase_order
    )
    return _generate_pdf(html, f"po_{purchase_order.po_number}.pdf")

def generate_invoice_pdf(invoice, line_items, vendor, purchase_order) -> str:
    html = _build_html(
        title="Invoice",
        doc_number=invoice.invoice_number,
        doc_date=invoice.invoice_date.strftime("%Y-%m-%d"),
        vendor=vendor,
        line_items=line_items,
        doc_obj=invoice,
        po_ref=purchase_order.po_number
    )
    return _generate_pdf(html, f"inv_{invoice.invoice_number}.pdf")
