"""module3_approval_trigger

Revision ID: 93ef976e9d14
Revises: a7f3c92e1d08
Create Date: 2026-06-06 10:18:01.410036+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ef976e9d14'
down_revision: Union[str, None] = 'a7f3c92e1d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_triggers',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_triggers_id'), 'approval_triggers', ['id'], unique=False)
    op.create_index(op.f('ix_approval_triggers_quotation_id'), 'approval_triggers', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_approval_triggers_rfq_id'), 'approval_triggers', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_approval_triggers_vendor_id'), 'approval_triggers', ['vendor_id'], unique=False)
    op.drop_constraint('quotations_quotation_number_key', 'quotations', type_='unique')
    op.drop_constraint('rfqs_rfq_number_key', 'rfqs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rfqs_rfq_number_key', 'rfqs', ['rfq_number'])
    op.create_unique_constraint('quotations_quotation_number_key', 'quotations', ['quotation_number'])
    op.drop_index(op.f('ix_approval_triggers_vendor_id'), table_name='approval_triggers')
    op.drop_index(op.f('ix_approval_triggers_rfq_id'), table_name='approval_triggers')
    op.drop_index(op.f('ix_approval_triggers_quotation_id'), table_name='approval_triggers')
    op.drop_index(op.f('ix_approval_triggers_id'), table_name='approval_triggers')
    op.drop_table('approval_triggers')
    # ### end Alembic commands ###
